config/routes.rb
Codest::Application.routes.draw do
  resources :answers

  resources :user_files do
    member { get 'download' }
  end

  resources :questions

  resources :reports, except: [:index, :show, :edit, :update, :destroy]

  namespace :setting do
    resources :questions do
      member { post 'same_password' }
    end
    get "top" => "top#index", as: "top" 
  end

  root 'top#index'

  

end

app/models/user_file.rb
class UserFile < ActiveRecord::Base
  validates :name, :content_type, :data, presence: true
  
  has_one :question
  has_one :answer

  def send_file file
   self.name = file.original_filename
   self.content_type = file.content_type
   self.data = file.read
  end
end

app/controllers/user_files_controller.rb
class UserFilesController < ApplicationController
  before_action :set_user_file, only: [:show, :edit, :update, :destroy]

  # GET /user_files
  # GET /user_files.json
  def index
    @user_files = UserFile.all
  end

  # GET /user_files/1
  # GET /user_files/1.json
  def show
  end

  # GET /user_files/new
  def new
    @user_file = UserFile.new
  end

  # GET /user_files/1/edit
  def edit
  end

  # POST /user_files
  # POST /user_files.json
  def create
    @user_file = UserFile.new()

    file = params[:user_file][:data]
     
    @user_file.name = file.original_filename
    @user_file.content_type = file.content_type
    @user_file.data = file.read

    respond_to do |format|
      if @user_file.save
        format.html { redirect_to @user_file, notice: 'Question file was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_file }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_files/1
  # PATCH/PUT /user_files/1.json
  def update
    @user_file = UserFile.find(params[:id])

    file = params[:user_file][:data]
     
    @user_file.name = file.original_filename
    @user_file.content_type = file.content_type
    @user_file.data = file.read

    respond_to do |format|
      if @user_file.save
        format.html { redirect_to @user_file, notice: 'Question file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_files/1
  # DELETE /user_files/1.json
  def destroy
    @user_file.destroy
    respond_to do |format|
      format.html { redirect_to user_files_url }
      format.json { head :no_content }
    end
  end

  def download
    @user_file = UserFile.find(params[:id])
    send_data(
      @user_file.data,
      filename: @user_file.name,
      content_type: @user_file.content_type
    )
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_file
      @user_file = UserFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_file_params
      params.require(:user_file).permit(:name, :content_type, :data)
    end
end

app/helpers/user_files_helper.rb
module UserFilesHelper
end

app/views/user_files/_form.html.erb
<%= form_for(@user_file, html: { multitype: true }) do |f| %>
  <% if @user_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_file.errors.count, "error") %> prohibited this user_file from being saved:</h2>

      <ul>
      <% @user_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.text_field :content_type %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.file_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_files/edit.html.erb
<h1>Editing user_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_file %> |
<%= link_to 'Back', user_files_path %>

app/views/user_files/index.html.erb
<h1>Listing user_files</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content type</th>
      <th>Data</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_files.each do |user_file| %>
      <tr>
        <td><%= user_file.name %></td>
        <td><%= user_file.content_type %></td>
        <td><%= link_to 'Show', user_file %></td>
        <td><%= link_to 'Edit', edit_user_file_path(user_file) %></td>
        <td><%= link_to 'Destroy', user_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question file', new_user_file_path %>

app/views/user_files/new.html.erb
<h1>New user_file</h1>

<%= render 'form' %>

<%= link_to 'Back', user_files_path %>

app/views/user_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_file.name %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @user_file.content_type %>
</p>

<p>
  <strong>Data:</strong>
  <%= link_to 'Download', download_user_file_path(@user_file) %>
</p>

<%= link_to 'Edit', edit_user_file_path(@user_file) %> |
<%= link_to 'Back', user_files_path %>