config/routes.rb
Codest::Application.routes.draw do
  resources :answers

  resources :user_files do
    member { get 'download' }
  end

  resources :questions

  resources :reports, except: [:index, :show, :edit, :update, :destroy]

  namespace :setting do
    resources :questions do
      member { post 'same_password' }
    end
    get "top" => "top#index", as: "top" 
  end

  root 'top#index'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :user_name, :question, :user_file, :email, presence: true

  belongs_to :user_file
  belongs_to :question

  accepts_nested_attributes_for :user_file

  def user_file_attributes= data
    u_data = data[:data]
    self.build_user_file
    self.user_file.send_file u_data
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include IllegalMethod
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
    @answer.build_user_file
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save && illegal_answer?(@answer.user_file.data)
        AnswerMail.send_mail(@answer).deliver
        format.html { render "feedback" }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)

        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:user_name, :question_id, :email, user_file_attributes: [:data])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<div class="thumbnail">
  <%= form_for(@answer, html: { multitype: true }) do |f| %>
    <% if @answer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
        <ul>
          <% @answer.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :question_id %>
      <%= f.select :question_id, Question.all.map{|q| [q.title, q.id] } %>
    </div>

    <div class="field">
      <%= f.label :user_name %>
      <%= f.text_field :user_name %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.fields_for :user_file_attributes do |uf| %>
        <%= uf.label :data %>
        <%= uf.file_field :data %>
      <% end %>
    </div>

    <div class="actions">
      <%= f.submit  "Send Report", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/feedback.html.erb
<h1>Feedback!!</h1>
<div class="thumbnail jumbotron">
  <div class="caption">
    <h2>出題者に解答が送信されました。</h2>
    Feedbackがくるのを待ちましょう！
  </div>
</div>


<%= link_to 'Back', root_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Question</th>
      <th>Email</th>
      <th>User_File</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.user_name %></td>
        <td><%= answer.question_id %></td>
        <td><%= answer.email %></td>
        <td><%= answer.user_file %></td>
        <td><%= link_to 'report', report_path(answer), method: :post %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @answer.user_name %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @answer.email %>
</p>

<p>
  <strong>User_File:</strong>
  <%= @answer.user_file %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>