config/routes.rb
Codest::Application.routes.draw do
  resources :answers

  resources :user_files do
    member { get 'download' }
  end

  resources :questions

  resources :reports, except: [:index, :show, :edit, :update, :destroy]

  namespace :setting do
    resources :questions do
      member { post 'same_password' }
    end
    get "top" => "top#index", as: "top" 
  end

  root 'top#index'

  

end

app/models/question.rb
require "bcrypt" 

class Question < ActiveRecord::Base
  attr_accessor :password

  validates :title, :content, :hash_password, :email, :user_file, presence: true
 
  belongs_to :user_file
  has_many :answers
  
  accepts_nested_attributes_for :user_file

  def user_file_attributes=(data)
    q_data = data[:data]
    self.build_user_file
    self.user_file.send_file q_data
  end

  def password=(pass)
    self.hash_password = BCrypt::Password.create(pass)
  end

  def same_password? password
    BCrypt::Password.new(self.hash_password) == password
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    @question.build_user_file
  end

  # GET /questions/1/edit
  def edit
    @question.build_user_file
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :password, :email, :content, :user_file_attributes => [:data])
    end
end

app/controllers/setting/questions_controller.rb
require 'bcrypt'

class Setting::QuestionsController < ApplicationController
  include IllegalMethod
  before_action :set_question, only: [:show, :edit, :update, :destroy, :same_password]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    @question.build_user_file
  end

  # GET /questions/1/edit
  def edit
    @question.build_user_file
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    respond_to do |format|
      if !illegal_question?(@question.user_file.data) && @question.save
        format.html { redirect_to [:setting, @question], notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /questions/1/same_password
  def same_password
    respond_to do |format|
      if @question.same_password? params[:password]
        @question.destroy
        format.html { redirect_to setting_questions_url }
      else
        format.html { render "show", location: @question }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to setting_questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :content, :password, :email, :user_file_attributes => [:data])
    end
end

app/controllers/setting/top_controller.rb
class Setting::TopController < ApplicationController
  def index
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/setting/questions/_form.html.erb
<div class="thumbnail">
<%= form_for([:setting, @question], html: { multitype: true }) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.fields_for :user_file_attributes do |uf| %>
      <%= uf.label :data %>
      <%= uf.file_field :data %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/setting/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/setting/questions/index.html.erb
<h1>Listing questions</h1>

<%= link_to "New Question", new_setting_question_path %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= truncate question.content, omission: "..." %></td>
        <td><%= link_to "show", setting_question_path(question.id), class: "btn btn-primary" %></td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/setting/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', setting_questions_path %>

app/views/setting/questions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="thumbnail jumbotron">
  <div class="caption">
    <div class="question_title">
      <h2><%= image_tag "question_mark.png" %>&nbsp;<%= @question.title %></h2>
    </div>
    <hr>
    <div class="question_content">
      <p><%= simple_format @question.content %><p>
    </div>
    <div>
      <p><%= link_to 'Download', download_user_file_path(@question.user_file), class: "btn btn-primary btn-lg", role: "button" %></p>
    </div>
    <div>
      <%= form_tag same_password_setting_question_path @question, method: :post do %>
        <div class="field">
          <%= label_tag "Delete password" %>
          <%= password_field_tag :password %>
        </div>
        <div class="actions">
          <%= submit_tag "delete", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'Back', setting_questions_path %>